server:
  port: 8001
spring:
  application:
    name: TEST-PROVIDER   #服务名称，随意取
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka #注册到Eureka的地址
