server:
  port: 8001
spring:
  application:
    name: server_provider_config   #服务名称，随意取

---
spring:
  cloud:
    config:
      label: master
      server:
        git:
          uri: "https://github.com/wpr8525/springCloudDemo.git"
          searchPaths: reo

#          username:
#          password: