server:
  port: 8001
spring:
  application:
    name: TEST-PROVIDER   #服务名称，随意取

---
spring:
  cloud:
    config:
      label: master
      server:
        git:
          uri: "https://github: com/forezp/SpringcloudConfig/"
          searchPaths: reo

#          username:
#          password: